### ISSUE TITLE
Prototypage Temporalis

### ISSUE THREAD

**Issue by PhilTrudel** [Orbital3/Temporalis#4]
# UPDATE
- [x]  Faire la sélection de questions
   -  Description: Faire la création de plusieurs questions pour le questionnaire.
- [x]  Avoir un questionnaire fonctionnel avec les questions
   - Description: Avoir un questionnaire où l'on peut sélectionner des boites et la question change peu importe la sélection
  - [x]  Faire un CountDown dans Unity
    - Description: Avoir un CountDown fonctionnel qui descend les secondes et les minutes
  - [x]  Faire la création des différents styles pour l'animateur - ***Rapporter en Production***
    - Description: Avoir différents types de style d'animateur pour faire la transition entre les différentes questions
- [x] Intégrer LeapMotion dans Unity - ***ÉCHEC***
- [x]  Pouvoir intégrer Arduino avec Unity
  - Description: Pouvoir avoir une connexion stable entre Arduino et Unity (par exemple quand je clique sur le bouton quelque chose arrive dans Unity)
- [x]  Pouvoir faire la sélection de questions avec Arduino - ***ÉCHEC***
  - Description: Pouvoir cliquer sur un bouton et une question est sélectionné dans Unity

**Comment by PhilTrudel** [comment]
J'ai testé la création d'un questionnaire sur unity en 3D au départ, sans succès, je me suis lancé sur un projet en 2D qui, avec un suivi d'un tutoriel en ligne, m'a donné un résultat concluant. Le problème est que j'ai suivi aussi un tutoriel de départ de Thomas et il y a un conflit entre écrire du code avec Input System et le vieux Input + C#. J'ai un problème pour démarrer mon jeu, mais sinon tout semble correct. 

J'aurais malgré tout, aimé faire de teste de unity en langague de programmation Bolt (Visual Scripting), puisque c'est plus simple. Il n'y a malheureusment très peu de donné en ligne qui explique cette langue, car elle est assez récente, et je ne veux pas déranger Thomas et lui demander de faire plus de vidéo explicatif.

Je vais trouver une meilleure solution prochainement.

**Comment by RFillion** [comment]
D'abord, notre projet comportait un élément nouveau : LeapMotion. On voulait l'utiliser pour faire la sélection de question grâce à un système de 'Swipe'. Cependant, en essayant de comprendre le fonctionnement de ce système, j'ai remarqué que la courbe d'apprentissage de ce nouveau système est trop grand pour le temps limité qu'on a. 

On a alors décidé d'orienté notre jeu vers quelque chose de plus physique avec des boutons connectés vers Unity pour faire la sélection de questions.

**Comment by RFillion** [comment]
Pour ce qui en est de la connexion entre Arduino et Unity, j'ai réussi grâce au notes de cours de Thomas de pouvoir faire disparaître un cube dans Unity en appuyant sur le bouton. 

Pour le prototypage, il va me rester à faire la connexion avec la scène de Philippe pour faire la sélection de chaque question.

**Comment by RFillion** [comment]
Le dernier point de la liste de tâche (Pouvoir faire la sélection de questions avec Arduino) n'a pas été un succès. Le problème que j'avais était que je ne pouvais simuler un clique avec le bouton arduino, ce qui n'activait pas ce que je voulais. Il faudra demander à Thomas pour une solution.
